"""
Shared data models for the secure document chatbot pipeline.

This module contains only structured data definitions. It does not contain
business logic, policy checks, AI-agent behavior, or execution logic.

These models are used across the full runtime flow:

AI Agent 1 proposes action
    ↓
AI Agent 2 reviews risk
    ↓
Rule-based policy engine enforces hard constraints
    ↓
Human approval if needed
    ↓
Executor runs approved action
"""

from dataclasses import dataclass
from enum import Enum
from typing import List, Optional


class DecisionType(Enum):
    """
    Possible decisions produced by the policy and control layers.

    ALLOW:
        The proposed action is safe and can be executed.

    CONSTRAIN:
        The proposed action may proceed only in a restricted or modified form,
        such as with redacted content.

    BLOCK:
        The proposed action is not allowed and must not be executed.

    REQUIRE_HUMAN_APPROVAL:
        The system cannot safely decide automatically, so a human reviewer
        must approve or reject the action.
    """

    ALLOW = "allow"
    CONSTRAIN = "constrain"
    BLOCK = "block"
    REQUIRE_HUMAN_APPROVAL = "require_human_approval"


@dataclass
class User:
    """
    Represents an employee using the internal document chatbot.

    Attributes:
        user_id:
            Unique identifier for the employee.

        name:
            Human-readable name of the employee.

        department:
            Department where the employee works, such as HR, Finance,
            Manufacturing, or Defense Engineering.

        clearance_level:
            Numeric access level assigned to the employee. A higher number
            means the user can access more restricted information.

        roles:
            Additional role-based permissions assigned to the employee.
            Example: ["employee", "cross_department_reader"].
    """

    user_id: str
    name: str
    department: str
    clearance_level: int
    roles: List[str]


@dataclass
class Document:
    """
    Represents an internal document in the organization archive.

    Attributes:
        document_id:
            Unique identifier for the document.

        title:
            Human-readable document title.

        department_owner:
            Department that owns or controls the document.

        classification_level:
            Numeric sensitivity level of the document. A higher number means
            the document contains more restricted information.

        content:
            Document text used by the chatbot when generating answers.
    """

    document_id: str
    title: str
    department_owner: str
    classification_level: int
    content: str


@dataclass
class ProposedAction:
    """
    Represents the action proposed by AI Agent 1.

    The chatbot should not execute this action directly. It must first be
    reviewed by the risk reviewer and policy engine.

    Attributes:
        action_type:
            Type of action the chatbot wants to perform.
            Example: "answer_document_question".

        user_query:
            Original question or request from the employee.

        requested_documents:
            List of document IDs the chatbot wants to use to answer the query.

        intended_answer:
            Draft answer generated by AI Agent 1 before safety checks.
    """

    action_type: str
    user_query: str
    requested_documents: List[str]
    intended_answer: str


@dataclass
class RiskReview:
    """
    Represents the risk assessment produced by AI Agent 2.

    AI Agent 2 can identify contextual risks, but it should not be the final
    authority. The deterministic policy engine must still enforce hard rules.

    Attributes:
        risk_level:
            Estimated risk level for the proposed action.
            Expected values: "low", "medium", or "high".

        concerns:
            Human-readable list of detected risks or warnings.

        recommendation:
            Suggested decision from the risk reviewer.
            The policy engine may still override this recommendation.
    """

    risk_level: str
    concerns: List[str]
    recommendation: DecisionType


@dataclass
class PolicyDecision:
    """
    Represents the final decision from the policy/control layer.

    The executor uses this object to decide whether the chatbot response should
    be shown, redacted, escalated, or blocked.

    Attributes:
        decision:
            Final decision type: allow, constrain, block, or require approval.

        reason:
            Human-readable explanation for the decision.

        allowed_documents:
            Optional list of document IDs that passed access checks.

        constrained_answer:
            Optional safe/redacted answer used when the decision is CONSTRAIN.
    """

    decision: DecisionType
    reason: str
    allowed_documents: Optional[List[str]] = None
    constrained_answer: Optional[str] = None
